# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://meowdevelopers.github.io"
baseurl: "" 
github_username : MeowDevelopers


#############
# HTML Head #
#############

lang: "ko-KR"
author: "Meow"
title: "Meow Develops"
description: "Meow 스터디 기록."
keywords: "Meow, Study, Develops"
favicon: "/img/favicon.ico"

################
# Header layout#
################
background-img: "intro-bg.png"

##############################
# Dynamic Text on the Header #
##############################

quote: "고양이와 같은 유연함을 가지고 싶은 개발자들"

#######
# Blog #
########
post-preview-words: 96
paginate: 25
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

# Sections shown in the index page
# pages_list:
#   Study Notes: "study-notes"

navigation_list:
  About: "about"
  Study Notes: "study-notes"
  Project: "project"

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml

# Pagination path
paginate_path: "/study-notes/page:num/"

sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
  # - jekyll-sitemap
  - jekyll-feed

